globals
    // Generated
rect gg_rct_BOTTOM_HALF= null
rect gg_rct_Mid= null
rect gg_rct_NE= null
rect gg_rct_NEF= null
rect gg_rct_Scourge_1= null
rect gg_rct_Scourge_2= null
rect gg_rct_Sentinel_1= null
rect gg_rct_Sentinel_2= null
rect gg_rct_SIDE_LEFT= null
rect gg_rct_SIDE_RIGHT= null
rect gg_rct_TOP_HALF= null
rect gg_rct_UF= null
rect gg_rct_Undead= null
string gg_snd_DarkAgents
string gg_snd_Doom


//JASSHelper struct globals:

endglobals


//===========================================================================
// 
// Slalom Wars 1.7
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Map Author: Daffa the Mage
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************


function InitGlobals takes nothing returns nothing
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************

//***************************************************************************
//*
//*  Sound Assets
//*
//***************************************************************************

function InitSounds takes nothing returns nothing
    set gg_snd_DarkAgents="DarkAgents"
    set gg_snd_Doom="Doom"
endfunction

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateBuildingsForPlayer0 takes nothing returns nothing
    local player p= Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'e000', - 8672.0, 1056.0, 270.000, 'e000')
    set u=BlzCreateUnitWithSkin(p, 'ncop', 3776.0, 1600.0, 270.000, 'ncop')
endfunction

//===========================================================================
function CreateBuildingsForPlayer1 takes nothing returns nothing
    local player p= Player(1)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'ncop', 3776.0, 1472.0, 270.000, 'ncop')
    set u=BlzCreateUnitWithSkin(p, 'e000', - 8672.0, 1824.0, 270.000, 'e000')
endfunction

//===========================================================================
function CreateBuildingsForPlayer2 takes nothing returns nothing
    local player p= Player(2)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'etrp', - 3296.0, 160.0, 270.000, 'etrp')
    set u=BlzCreateUnitWithSkin(p, 'etrp', - 3296.0, 3040.0, 270.000, 'etrp')
    set u=BlzCreateUnitWithSkin(p, 'etrp', - 6688.0, 1504.0, 270.000, 'etrp')
    set u=BlzCreateUnitWithSkin(p, 'etrp', - 6816.0, - 224.0, 270.000, 'etrp')
    set u=BlzCreateUnitWithSkin(p, 'etrp', - 6880.0, 3936.0, 270.000, 'etrp')
    set u=BlzCreateUnitWithSkin(p, 'etrp', - 8224.0, 1760.0, 270.000, 'etrp')
    set u=BlzCreateUnitWithSkin(p, 'etrp', - 8224.0, 2464.0, 270.000, 'etrp')
    set u=BlzCreateUnitWithSkin(p, 'etrp', - 8224.0, 1120.0, 270.000, 'etrp')
    set u=BlzCreateUnitWithSkin(p, 'emow', - 9248.0, 3232.0, 270.000, 'emow')
    set u=BlzCreateUnitWithSkin(p, 'emow', - 9248.0, 3040.0, 270.000, 'emow')
    set u=BlzCreateUnitWithSkin(p, 'emow', - 9312.0, 608.0, 270.000, 'emow')
    set u=BlzCreateUnitWithSkin(p, 'emow', - 9312.0, 416.0, 270.000, 'emow')
endfunction

//===========================================================================
function CreateBuildingsForPlayer3 takes nothing returns nothing
    local player p= Player(3)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'ncop', 3776.0, 1344.0, 270.000, 'ncop')
    set u=BlzCreateUnitWithSkin(p, 'e000', - 8672.0, 2528.0, 270.000, 'e000')
endfunction

//===========================================================================
function CreateBuildingsForPlayer4 takes nothing returns nothing
    local player p= Player(4)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'ncop', 4288.0, 1344.0, 270.000, 'ncop')
    set u=BlzCreateUnitWithSkin(p, 'u000', 17120.0, 992.0, 270.000, 'u000')
endfunction

//===========================================================================
function CreateBuildingsForPlayer5 takes nothing returns nothing
    local player p= Player(5)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'ncop', 4288.0, 1472.0, 270.000, 'ncop')
    set u=BlzCreateUnitWithSkin(p, 'u000', 17056.0, 1760.0, 270.000, 'u000')
endfunction

//===========================================================================
function CreateBuildingsForPlayer6 takes nothing returns nothing
    local player p= Player(6)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'uzg1', 11424.0, 480.0, 270.000, 'uzg1')
    set u=BlzCreateUnitWithSkin(p, 'uzg1', 11552.0, 3168.0, 270.000, 'uzg1')
    set u=BlzCreateUnitWithSkin(p, 'uzg1', 15392.0, - 224.0, 270.000, 'uzg1')
    set u=BlzCreateUnitWithSkin(p, 'uzg1', 15456.0, 3168.0, 270.000, 'uzg1')
    set u=BlzCreateUnitWithSkin(p, 'uzg1', 16736.0, 992.0, 270.000, 'uzg1')
    set u=BlzCreateUnitWithSkin(p, 'uzg1', 16672.0, 1760.0, 270.000, 'uzg1')
    set u=BlzCreateUnitWithSkin(p, 'uzg1', 16608.0, 2656.0, 270.000, 'uzg1')
    set u=BlzCreateUnitWithSkin(p, 'uzig', 17696.0, 160.0, 270.000, 'uzig')
    set u=BlzCreateUnitWithSkin(p, 'uzig', 17696.0, 480.0, 270.000, 'uzig')
    set u=BlzCreateUnitWithSkin(p, 'uzig', 17632.0, 2912.0, 270.000, 'uzig')
    set u=BlzCreateUnitWithSkin(p, 'uzig', 17632.0, 3232.0, 270.000, 'uzig')
endfunction

//===========================================================================
function CreateBuildingsForPlayer7 takes nothing returns nothing
    local player p= Player(7)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'ncop', 4288.0, 1600.0, 270.000, 'ncop')
    set u=BlzCreateUnitWithSkin(p, 'u000', 16992.0, 2592.0, 270.000, 'u000')
endfunction

//===========================================================================
function CreateBuildingsForPlayer8 takes nothing returns nothing
    local player p= Player(8)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'u001', 5216.0, - 608.0, 270.000, 'u001')
    set u=BlzCreateUnitWithSkin(p, 'u001', 6496.0, - 480.0, 270.000, 'u001')
    set u=BlzCreateUnitWithSkin(p, 'u001', 5280.0, 3744.0, 270.000, 'u001')
    set u=BlzCreateUnitWithSkin(p, 'u001', 6432.0, 3552.0, 270.000, 'u001')
    set u=BlzCreateUnitWithSkin(p, 'u006', 7904.0, - 480.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 7968.0, 3552.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 14816.0, 1376.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 15008.0, 1184.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 14816.0, 2080.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 15008.0, 2080.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 14816.0, 1184.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 15008.0, 1376.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 14816.0, 1888.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 15008.0, 1888.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 15200.0, 1888.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 15200.0, 1376.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 15200.0, 2080.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'u006', 15200.0, 1184.0, 270.000, 'u006')
    set u=BlzCreateUnitWithSkin(p, 'h00G', 16192.0, 1728.0, 270.000, 'h00G')
endfunction

//===========================================================================
function CreateBuildingsForPlayer9 takes nothing returns nothing
    local player p= Player(9)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'e001', - 6496.0, 2208.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e008', 3232.0, - 672.0, 270.000, 'e008')
    set u=BlzCreateUnitWithSkin(p, 'e008', 1760.0, - 352.0, 270.000, 'e008')
    set u=BlzCreateUnitWithSkin(p, 'e008', 1824.0, 3360.0, 270.000, 'e008')
    set u=BlzCreateUnitWithSkin(p, 'e008', 3168.0, 3552.0, 270.000, 'e008')
    set u=BlzCreateUnitWithSkin(p, 'e001', 160.0, - 352.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', 160.0, 3296.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', - 6496.0, 1312.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', - 6688.0, 2208.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', - 6688.0, 1312.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', - 6496.0, 1504.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', - 6496.0, 2016.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', - 6688.0, 2016.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', - 6880.0, 1504.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', - 6880.0, 2016.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', - 6880.0, 1312.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'e001', - 6880.0, 2208.0, 270.000, 'e001')
    set u=BlzCreateUnitWithSkin(p, 'h00F', - 7744.0, 1728.0, 270.000, 'h00F')
endfunction

//===========================================================================
function CreateBuildingsForPlayer10 takes nothing returns nothing
    local player p= Player(10)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'e000', - 8992.0, 1824.0, 270.000, 'e000')
    set u=BlzCreateUnitWithSkin(p, 'ncop', 3776.0, 1216.0, 270.000, 'ncop')
endfunction

//===========================================================================
function CreateBuildingsForPlayer11 takes nothing returns nothing
    local player p= Player(11)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'u000', 17440.0, 1760.0, 270.000, 'u000')
    set u=BlzCreateUnitWithSkin(p, 'ncop', 4288.0, 1216.0, 270.000, 'ncop')
endfunction

//===========================================================================
function CreateBuildingsForPlayer12 takes nothing returns nothing
    local player p= Player(12)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'u000', 17376.0, 2656.0, 270.000, 'u000')
    set u=BlzCreateUnitWithSkin(p, 'ncop', 4288.0, 1088.0, 270.000, 'ncop')
endfunction

//===========================================================================
function CreateBuildingsForPlayer13 takes nothing returns nothing
    local player p= Player(13)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'e000', - 8992.0, 2528.0, 270.000, 'e000')
    set u=BlzCreateUnitWithSkin(p, 'ncop', 3776.0, 1088.0, 270.000, 'ncop')
endfunction

//===========================================================================
function CreateBuildingsForPlayer14 takes nothing returns nothing
    local player p= Player(14)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'e000', - 8992.0, 1056.0, 270.000, 'e000')
    set u=BlzCreateUnitWithSkin(p, 'ncop', 3776.0, 960.0, 270.000, 'ncop')
endfunction

//===========================================================================
function CreateBuildingsForPlayer15 takes nothing returns nothing
    local player p= Player(15)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'u000', 17440.0, 992.0, 270.000, 'u000')
    set u=BlzCreateUnitWithSkin(p, 'ncop', 4288.0, 960.0, 270.000, 'ncop')
endfunction

//===========================================================================
function CreateNeutralPassiveBuildings takes nothing returns nothing
    local player p= Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u=BlzCreateUnitWithSkin(p, 'ngol', - 10816.0, 1856.0, 270.000, 'ngol')
    call SetResourceAmount(u, 1000000)
    set u=BlzCreateUnitWithSkin(p, 'ngol', 19008.0, 1984.0, 270.000, 'ngol')
    call SetResourceAmount(u, 1000000)
    set u=BlzCreateUnitWithSkin(p, 'h000', - 6336.0, 1472.0, 270.000, 'h000')
    set u=BlzCreateUnitWithSkin(p, 'h003', - 6208.0, 1472.0, 270.000, 'h003')
    set u=BlzCreateUnitWithSkin(p, 'h002', - 6336.0, 1984.0, 270.000, 'h002')
    set u=BlzCreateUnitWithSkin(p, 'h001', - 6208.0, 1984.0, 270.000, 'h001')
    set u=BlzCreateUnitWithSkin(p, 'nfoh', - 5824.0, 1728.0, 270.000, 'nfoh')
    set u=BlzCreateUnitWithSkin(p, 'h003', 14528.0, 1408.0, 270.000, 'h003')
    set u=BlzCreateUnitWithSkin(p, 'h000', 14656.0, 1408.0, 270.000, 'h000')
    set u=BlzCreateUnitWithSkin(p, 'nfoh', 14208.0, 1600.0, 270.000, 'nfoh')
    set u=BlzCreateUnitWithSkin(p, 'h001', 14528.0, 1856.0, 270.000, 'h001')
    set u=BlzCreateUnitWithSkin(p, 'h002', 14656.0, 1856.0, 270.000, 'h002')
    set u=BlzCreateUnitWithSkin(p, 'n001', 3520.0, 1344.0, 270.000, 'n001')
    set u=BlzCreateUnitWithSkin(p, 'n002', 4544.0, 1344.0, 270.000, 'n002')
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 10816.0, - 2560.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 10752.0, 5504.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 18944.0, 5440.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 18880.0, - 2048.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 320.0, - 2368.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 2304.0, - 2304.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 4544.0, - 2368.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 6528.0, - 2496.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 7808.0, - 2368.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 7808.0, 5632.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 6400.0, 5504.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 4288.0, 5568.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 2240.0, 5248.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, - 320.0, 5568.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 1728.0, 5568.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 2368.0, - 2368.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 4032.0, 5248.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 4160.0, - 2432.0, 270.000, unitID)
    endif
    set u=BlzCreateUnitWithSkin(p, 'h009', 12736.0, 1600.0, 270.000, 'h009')
    set u=BlzCreateUnitWithSkin(p, 'h00B', - 6208.0, 2112.0, 270.000, 'h00B')
    set u=BlzCreateUnitWithSkin(p, 'h009', - 4416.0, 1856.0, 270.000, 'h009')
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 6464.0, 5312.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 10624.0, 5248.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 8640.0, 5312.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 12864.0, 5376.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 14912.0, 5376.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 16064.0, 5312.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 16064.0, - 2304.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 14912.0, - 2240.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 12672.0, - 2368.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 10688.0, - 2240.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 8640.0, - 2304.0, 270.000, unitID)
    endif
    set unitID=ChooseRandomNPBuilding()
    if ( unitID != - 1 ) then
        set u=BlzCreateUnitWithSkin(p, unitID, 6400.0, - 2304.0, 270.000, unitID)
    endif
    set u=BlzCreateUnitWithSkin(p, 'h00B', 14528.0, 1984.0, 270.000, 'h00B')
    set u=BlzCreateUnitWithSkin(p, 'h003', 6272.0, 1472.0, 270.000, 'h003')
    set u=BlzCreateUnitWithSkin(p, 'n009', 4032.0, 1344.0, 270.000, 'n009')
    set u=BlzCreateUnitWithSkin(p, 'h003', 1152.0, 832.0, 270.000, 'h003')
    set u=BlzCreateUnitWithSkin(p, 'h003', 1024.0, 2176.0, 270.000, 'h003')
    set u=BlzCreateUnitWithSkin(p, 'h003', 7232.0, 896.0, 270.000, 'h003')
    set u=BlzCreateUnitWithSkin(p, 'h003', 7168.0, 2112.0, 270.000, 'h003')
    set u=BlzCreateUnitWithSkin(p, 'ngol', - 128.0, 1536.0, 270.000, 'ngol')
    call SetResourceAmount(u, 1000000)
    set u=BlzCreateUnitWithSkin(p, 'ngol', 8640.0, 1664.0, 270.000, 'ngol')
    call SetResourceAmount(u, 1000000)
    set u=BlzCreateUnitWithSkin(p, 'h00H', 14656.0, 1280.0, 270.000, 'h00H')
    set u=BlzCreateUnitWithSkin(p, 'h00H', - 6336.0, 1344.0, 270.000, 'h00H')
    set u=BlzCreateUnitWithSkin(p, 'h00I', - 5824.0, 1472.0, 270.000, 'h00I')
    set u=BlzCreateUnitWithSkin(p, 'h00I', 14208.0, 1344.0, 270.000, 'h00I')
    set u=BlzCreateUnitWithSkin(p, 'h00K', 4032.0, 2176.0, 270.000, 'h00K')
    set u=BlzCreateUnitWithSkin(p, 'h00J', - 6208.0, 1344.0, 270.000, 'h00J')
    set u=BlzCreateUnitWithSkin(p, 'h00J', 14528.0, 1280.0, 270.000, 'h00J')
    set u=BlzCreateUnitWithSkin(p, 'h003', 2112.0, 1408.0, 270.000, 'h003')
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
    call CreateBuildingsForPlayer0()
    call CreateBuildingsForPlayer1()
    call CreateBuildingsForPlayer2()
    call CreateBuildingsForPlayer3()
    call CreateBuildingsForPlayer4()
    call CreateBuildingsForPlayer5()
    call CreateBuildingsForPlayer6()
    call CreateBuildingsForPlayer7()
    call CreateBuildingsForPlayer8()
    call CreateBuildingsForPlayer9()
    call CreateBuildingsForPlayer10()
    call CreateBuildingsForPlayer11()
    call CreateBuildingsForPlayer12()
    call CreateBuildingsForPlayer13()
    call CreateBuildingsForPlayer14()
    call CreateBuildingsForPlayer15()
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreateNeutralPassiveBuildings()
    call CreatePlayerBuildings()
    call CreatePlayerUnits()
endfunction

//***************************************************************************
//*
//*  Regions
//*
//***************************************************************************

function CreateRegions takes nothing returns nothing
    local weathereffect we

    set gg_rct_BOTTOM_HALF=Rect(- 11584.0, - 2912.0, 19840.0, 832.0)
    set gg_rct_Mid=Rect(3552.0, 928.0, 4768.0, 2016.0)
    set gg_rct_NE=Rect(- 8064.0, 1376.0, - 7424.0, 2112.0)
    set gg_rct_NEF=Rect(- 6272.0, 1440.0, - 6048.0, 2016.0)
    set gg_rct_Scourge_1=Rect(16416.0, - 1056.0, 17440.0, - 224.0)
    set gg_rct_Scourge_2=Rect(16512.0, 3872.0, 17536.0, 4704.0)
    set gg_rct_Sentinel_1=Rect(- 9056.0, 3744.0, - 8032.0, 4576.0)
    set gg_rct_Sentinel_2=Rect(- 9152.0, - 1024.0, - 8128.0, - 192.0)
    set gg_rct_SIDE_LEFT=Rect(- 12288.0, - 4096.0, 4224.0, 8192.0)
    set gg_rct_SIDE_RIGHT=Rect(3968.0, - 4096.0, 20480.0, 8192.0)
    set gg_rct_TOP_HALF=Rect(- 11648.0, 2816.0, 19776.0, 6368.0)
    set gg_rct_UF=Rect(14272.0, 1280.0, 14624.0, 1888.0)
    set gg_rct_Undead=Rect(15872.0, 1376.0, 16512.0, 2144.0)
endfunction

//***************************************************************************
//*
//*  TechTree
//*
//***************************************************************************

function InitTechTree_Player0 takes nothing returns nothing
    call SetPlayerTechMaxAllowed(Player(0), 'eate', 0)
    call SetPlayerTechMaxAllowed(Player(0), 'uaod', 0)
    call SetPlayerTechMaxAllowed(Player(0), 'oalt', 0)
    call SetPlayerTechMaxAllowed(Player(0), 'halt', 0)
endfunction

function InitTechTree_Player1 takes nothing returns nothing
    call SetPlayerTechMaxAllowed(Player(1), 'eate', 0)
    call SetPlayerTechMaxAllowed(Player(1), 'uaod', 0)
    call SetPlayerTechMaxAllowed(Player(1), 'oalt', 0)
    call SetPlayerTechMaxAllowed(Player(1), 'halt', 0)
endfunction

function InitTechTree_Player3 takes nothing returns nothing
    call SetPlayerTechMaxAllowed(Player(3), 'eate', 0)
    call SetPlayerTechMaxAllowed(Player(3), 'uaod', 0)
    call SetPlayerTechMaxAllowed(Player(3), 'oalt', 0)
    call SetPlayerTechMaxAllowed(Player(3), 'halt', 0)
endfunction

function InitTechTree_Player4 takes nothing returns nothing
    call SetPlayerTechMaxAllowed(Player(4), 'eate', 0)
    call SetPlayerTechMaxAllowed(Player(4), 'uaod', 0)
    call SetPlayerTechMaxAllowed(Player(4), 'oalt', 0)
    call SetPlayerTechMaxAllowed(Player(4), 'halt', 0)
endfunction

function InitTechTree_Player5 takes nothing returns nothing
    call SetPlayerTechMaxAllowed(Player(5), 'eate', 0)
    call SetPlayerTechMaxAllowed(Player(5), 'uaod', 0)
    call SetPlayerTechMaxAllowed(Player(5), 'oalt', 0)
    call SetPlayerTechMaxAllowed(Player(5), 'halt', 0)
endfunction

function InitTechTree_Player7 takes nothing returns nothing
    call SetPlayerTechMaxAllowed(Player(7), 'eate', 0)
    call SetPlayerTechMaxAllowed(Player(7), 'uaod', 0)
    call SetPlayerTechMaxAllowed(Player(7), 'oalt', 0)
    call SetPlayerTechMaxAllowed(Player(7), 'halt', 0)
endfunction

function InitTechTree takes nothing returns nothing
    call InitTechTree_Player0()
    call InitTechTree_Player1()
    call InitTechTree_Player3()
    call InitTechTree_Player4()
    call InitTechTree_Player5()
    call InitTechTree_Player7()
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation(Player(0), 0)
    call ForcePlayerStartLocation(Player(0), 0)
    call SetPlayerColor(Player(0), ConvertPlayerColor(0))
    call SetPlayerRacePreference(Player(0), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(0), false)
    call SetPlayerController(Player(0), MAP_CONTROL_USER)

    // Player 1
    call SetPlayerStartLocation(Player(1), 1)
    call ForcePlayerStartLocation(Player(1), 1)
    call SetPlayerColor(Player(1), ConvertPlayerColor(1))
    call SetPlayerRacePreference(Player(1), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(1), false)
    call SetPlayerController(Player(1), MAP_CONTROL_USER)

    // Player 2
    call SetPlayerStartLocation(Player(2), 2)
    call ForcePlayerStartLocation(Player(2), 2)
    call SetPlayerColor(Player(2), ConvertPlayerColor(2))
    call SetPlayerRacePreference(Player(2), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(2), false)
    call SetPlayerController(Player(2), MAP_CONTROL_COMPUTER)

    // Player 3
    call SetPlayerStartLocation(Player(3), 3)
    call ForcePlayerStartLocation(Player(3), 3)
    call SetPlayerColor(Player(3), ConvertPlayerColor(3))
    call SetPlayerRacePreference(Player(3), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(3), false)
    call SetPlayerController(Player(3), MAP_CONTROL_USER)

    // Player 4
    call SetPlayerStartLocation(Player(4), 4)
    call ForcePlayerStartLocation(Player(4), 4)
    call SetPlayerColor(Player(4), ConvertPlayerColor(4))
    call SetPlayerRacePreference(Player(4), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(4), false)
    call SetPlayerController(Player(4), MAP_CONTROL_USER)

    // Player 5
    call SetPlayerStartLocation(Player(5), 5)
    call ForcePlayerStartLocation(Player(5), 5)
    call SetPlayerColor(Player(5), ConvertPlayerColor(5))
    call SetPlayerRacePreference(Player(5), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(5), false)
    call SetPlayerController(Player(5), MAP_CONTROL_USER)

    // Player 6
    call SetPlayerStartLocation(Player(6), 6)
    call ForcePlayerStartLocation(Player(6), 6)
    call SetPlayerColor(Player(6), ConvertPlayerColor(6))
    call SetPlayerRacePreference(Player(6), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(6), false)
    call SetPlayerController(Player(6), MAP_CONTROL_COMPUTER)

    // Player 7
    call SetPlayerStartLocation(Player(7), 7)
    call ForcePlayerStartLocation(Player(7), 7)
    call SetPlayerColor(Player(7), ConvertPlayerColor(7))
    call SetPlayerRacePreference(Player(7), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(7), false)
    call SetPlayerController(Player(7), MAP_CONTROL_USER)

    // Player 8
    call SetPlayerStartLocation(Player(8), 8)
    call ForcePlayerStartLocation(Player(8), 8)
    call SetPlayerColor(Player(8), ConvertPlayerColor(8))
    call SetPlayerRacePreference(Player(8), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(8), false)
    call SetPlayerController(Player(8), MAP_CONTROL_COMPUTER)

    // Player 9
    call SetPlayerStartLocation(Player(9), 9)
    call ForcePlayerStartLocation(Player(9), 9)
    call SetPlayerColor(Player(9), ConvertPlayerColor(9))
    call SetPlayerRacePreference(Player(9), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(9), false)
    call SetPlayerController(Player(9), MAP_CONTROL_COMPUTER)

    // Player 10
    call SetPlayerStartLocation(Player(10), 10)
    call ForcePlayerStartLocation(Player(10), 10)
    call SetPlayerColor(Player(10), ConvertPlayerColor(10))
    call SetPlayerRacePreference(Player(10), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(10), false)
    call SetPlayerController(Player(10), MAP_CONTROL_USER)

    // Player 11
    call SetPlayerStartLocation(Player(11), 11)
    call ForcePlayerStartLocation(Player(11), 11)
    call SetPlayerColor(Player(11), ConvertPlayerColor(11))
    call SetPlayerRacePreference(Player(11), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(11), false)
    call SetPlayerController(Player(11), MAP_CONTROL_USER)

    // Player 12
    call SetPlayerStartLocation(Player(12), 12)
    call ForcePlayerStartLocation(Player(12), 12)
    call SetPlayerColor(Player(12), ConvertPlayerColor(12))
    call SetPlayerRacePreference(Player(12), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(12), false)
    call SetPlayerController(Player(12), MAP_CONTROL_USER)

    // Player 13
    call SetPlayerStartLocation(Player(13), 13)
    call ForcePlayerStartLocation(Player(13), 13)
    call SetPlayerColor(Player(13), ConvertPlayerColor(13))
    call SetPlayerRacePreference(Player(13), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(13), false)
    call SetPlayerController(Player(13), MAP_CONTROL_USER)

    // Player 14
    call SetPlayerStartLocation(Player(14), 14)
    call ForcePlayerStartLocation(Player(14), 14)
    call SetPlayerColor(Player(14), ConvertPlayerColor(14))
    call SetPlayerRacePreference(Player(14), RACE_PREF_NIGHTELF)
    call SetPlayerRaceSelectable(Player(14), false)
    call SetPlayerController(Player(14), MAP_CONTROL_USER)

    // Player 15
    call SetPlayerStartLocation(Player(15), 15)
    call ForcePlayerStartLocation(Player(15), 15)
    call SetPlayerColor(Player(15), ConvertPlayerColor(15))
    call SetPlayerRacePreference(Player(15), RACE_PREF_UNDEAD)
    call SetPlayerRaceSelectable(Player(15), false)
    call SetPlayerController(Player(15), MAP_CONTROL_USER)

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_014
    call SetPlayerTeam(Player(0), 0)
    call SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(1), 0)
    call SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(2), 0)
    call SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(3), 0)
    call SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(9), 0)
    call SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(10), 0)
    call SetPlayerState(Player(10), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(13), 0)
    call SetPlayerState(Player(13), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(14), 0)
    call SetPlayerState(Player(14), PLAYER_STATE_ALLIED_VICTORY, 1)

    //   Allied
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(9), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(10), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(13), true)
    call SetPlayerAllianceStateAllyBJ(Player(0), Player(14), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(9), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(10), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(13), true)
    call SetPlayerAllianceStateAllyBJ(Player(1), Player(14), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(9), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(10), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(13), true)
    call SetPlayerAllianceStateAllyBJ(Player(2), Player(14), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(9), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(10), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(13), true)
    call SetPlayerAllianceStateAllyBJ(Player(3), Player(14), true)
    call SetPlayerAllianceStateAllyBJ(Player(9), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(9), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(9), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(9), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(9), Player(10), true)
    call SetPlayerAllianceStateAllyBJ(Player(9), Player(13), true)
    call SetPlayerAllianceStateAllyBJ(Player(9), Player(14), true)
    call SetPlayerAllianceStateAllyBJ(Player(10), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(10), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(10), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(10), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(10), Player(9), true)
    call SetPlayerAllianceStateAllyBJ(Player(10), Player(13), true)
    call SetPlayerAllianceStateAllyBJ(Player(10), Player(14), true)
    call SetPlayerAllianceStateAllyBJ(Player(13), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(13), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(13), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(13), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(13), Player(9), true)
    call SetPlayerAllianceStateAllyBJ(Player(13), Player(10), true)
    call SetPlayerAllianceStateAllyBJ(Player(13), Player(14), true)
    call SetPlayerAllianceStateAllyBJ(Player(14), Player(0), true)
    call SetPlayerAllianceStateAllyBJ(Player(14), Player(1), true)
    call SetPlayerAllianceStateAllyBJ(Player(14), Player(2), true)
    call SetPlayerAllianceStateAllyBJ(Player(14), Player(3), true)
    call SetPlayerAllianceStateAllyBJ(Player(14), Player(9), true)
    call SetPlayerAllianceStateAllyBJ(Player(14), Player(10), true)
    call SetPlayerAllianceStateAllyBJ(Player(14), Player(13), true)

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(9), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(10), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(13), true)
    call SetPlayerAllianceStateVisionBJ(Player(0), Player(14), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(9), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(10), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(13), true)
    call SetPlayerAllianceStateVisionBJ(Player(1), Player(14), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(9), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(10), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(13), true)
    call SetPlayerAllianceStateVisionBJ(Player(2), Player(14), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(9), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(10), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(13), true)
    call SetPlayerAllianceStateVisionBJ(Player(3), Player(14), true)
    call SetPlayerAllianceStateVisionBJ(Player(9), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(9), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(9), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(9), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(9), Player(10), true)
    call SetPlayerAllianceStateVisionBJ(Player(9), Player(13), true)
    call SetPlayerAllianceStateVisionBJ(Player(9), Player(14), true)
    call SetPlayerAllianceStateVisionBJ(Player(10), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(10), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(10), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(10), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(10), Player(9), true)
    call SetPlayerAllianceStateVisionBJ(Player(10), Player(13), true)
    call SetPlayerAllianceStateVisionBJ(Player(10), Player(14), true)
    call SetPlayerAllianceStateVisionBJ(Player(13), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(13), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(13), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(13), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(13), Player(9), true)
    call SetPlayerAllianceStateVisionBJ(Player(13), Player(10), true)
    call SetPlayerAllianceStateVisionBJ(Player(13), Player(14), true)
    call SetPlayerAllianceStateVisionBJ(Player(14), Player(0), true)
    call SetPlayerAllianceStateVisionBJ(Player(14), Player(1), true)
    call SetPlayerAllianceStateVisionBJ(Player(14), Player(2), true)
    call SetPlayerAllianceStateVisionBJ(Player(14), Player(3), true)
    call SetPlayerAllianceStateVisionBJ(Player(14), Player(9), true)
    call SetPlayerAllianceStateVisionBJ(Player(14), Player(10), true)
    call SetPlayerAllianceStateVisionBJ(Player(14), Player(13), true)

    // Force: TRIGSTR_015
    call SetPlayerTeam(Player(4), 1)
    call SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(5), 1)
    call SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(6), 1)
    call SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(7), 1)
    call SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(8), 1)
    call SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(11), 1)
    call SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(12), 1)
    call SetPlayerState(Player(12), PLAYER_STATE_ALLIED_VICTORY, 1)
    call SetPlayerTeam(Player(15), 1)
    call SetPlayerState(Player(15), PLAYER_STATE_ALLIED_VICTORY, 1)

    //   Allied
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(11), true)
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(12), true)
    call SetPlayerAllianceStateAllyBJ(Player(4), Player(15), true)
    call SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(5), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(5), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(5), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(5), Player(11), true)
    call SetPlayerAllianceStateAllyBJ(Player(5), Player(12), true)
    call SetPlayerAllianceStateAllyBJ(Player(5), Player(15), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(5), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(11), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(12), true)
    call SetPlayerAllianceStateAllyBJ(Player(6), Player(15), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(5), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(11), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(12), true)
    call SetPlayerAllianceStateAllyBJ(Player(7), Player(15), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(5), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(11), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(12), true)
    call SetPlayerAllianceStateAllyBJ(Player(8), Player(15), true)
    call SetPlayerAllianceStateAllyBJ(Player(11), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(11), Player(5), true)
    call SetPlayerAllianceStateAllyBJ(Player(11), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(11), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(11), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(11), Player(12), true)
    call SetPlayerAllianceStateAllyBJ(Player(11), Player(15), true)
    call SetPlayerAllianceStateAllyBJ(Player(12), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(12), Player(5), true)
    call SetPlayerAllianceStateAllyBJ(Player(12), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(12), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(12), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(12), Player(11), true)
    call SetPlayerAllianceStateAllyBJ(Player(12), Player(15), true)
    call SetPlayerAllianceStateAllyBJ(Player(15), Player(4), true)
    call SetPlayerAllianceStateAllyBJ(Player(15), Player(5), true)
    call SetPlayerAllianceStateAllyBJ(Player(15), Player(6), true)
    call SetPlayerAllianceStateAllyBJ(Player(15), Player(7), true)
    call SetPlayerAllianceStateAllyBJ(Player(15), Player(8), true)
    call SetPlayerAllianceStateAllyBJ(Player(15), Player(11), true)
    call SetPlayerAllianceStateAllyBJ(Player(15), Player(12), true)

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(11), true)
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(12), true)
    call SetPlayerAllianceStateVisionBJ(Player(4), Player(15), true)
    call SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(5), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(5), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(5), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(5), Player(11), true)
    call SetPlayerAllianceStateVisionBJ(Player(5), Player(12), true)
    call SetPlayerAllianceStateVisionBJ(Player(5), Player(15), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(5), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(11), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(12), true)
    call SetPlayerAllianceStateVisionBJ(Player(6), Player(15), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(5), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(11), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(12), true)
    call SetPlayerAllianceStateVisionBJ(Player(7), Player(15), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(5), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(11), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(12), true)
    call SetPlayerAllianceStateVisionBJ(Player(8), Player(15), true)
    call SetPlayerAllianceStateVisionBJ(Player(11), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(11), Player(5), true)
    call SetPlayerAllianceStateVisionBJ(Player(11), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(11), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(11), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(11), Player(12), true)
    call SetPlayerAllianceStateVisionBJ(Player(11), Player(15), true)
    call SetPlayerAllianceStateVisionBJ(Player(12), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(12), Player(5), true)
    call SetPlayerAllianceStateVisionBJ(Player(12), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(12), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(12), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(12), Player(11), true)
    call SetPlayerAllianceStateVisionBJ(Player(12), Player(15), true)
    call SetPlayerAllianceStateVisionBJ(Player(15), Player(4), true)
    call SetPlayerAllianceStateVisionBJ(Player(15), Player(5), true)
    call SetPlayerAllianceStateVisionBJ(Player(15), Player(6), true)
    call SetPlayerAllianceStateVisionBJ(Player(15), Player(7), true)
    call SetPlayerAllianceStateVisionBJ(Player(15), Player(8), true)
    call SetPlayerAllianceStateVisionBJ(Player(15), Player(11), true)
    call SetPlayerAllianceStateVisionBJ(Player(15), Player(12), true)

endfunction

function InitAllyPriorities takes nothing returns nothing

    call SetStartLocPrioCount(0, 2)
    call SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(0, 1, 2, MAP_LOC_PRIO_HIGH)

    call SetStartLocPrioCount(1, 2)
    call SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_LOW)

    call SetStartLocPrioCount(2, 2)
    call SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(2, 1, 1, MAP_LOC_PRIO_HIGH)

    call SetStartLocPrioCount(3, 3)
    call SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_LOW)
    call SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_LOW)
    call SetStartLocPrio(3, 2, 2, MAP_LOC_PRIO_LOW)

    call SetStartLocPrioCount(4, 2)
    call SetStartLocPrio(4, 0, 5, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(4, 1, 6, MAP_LOC_PRIO_HIGH)

    call SetStartLocPrioCount(5, 2)
    call SetStartLocPrio(5, 0, 4, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(5, 1, 6, MAP_LOC_PRIO_HIGH)

    call SetStartLocPrioCount(6, 2)
    call SetStartLocPrio(6, 0, 4, MAP_LOC_PRIO_HIGH)
    call SetStartLocPrio(6, 1, 5, MAP_LOC_PRIO_HIGH)

    call SetStartLocPrioCount(7, 3)
    call SetStartLocPrio(7, 0, 4, MAP_LOC_PRIO_LOW)
    call SetStartLocPrio(7, 1, 5, MAP_LOC_PRIO_LOW)
    call SetStartLocPrio(7, 2, 6, MAP_LOC_PRIO_LOW)
endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds(- 11520.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), - 3200.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 19712.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 6272.0 - GetCameraMargin(CAMERA_MARGIN_TOP), - 11520.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 6272.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 19712.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), - 3200.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    call SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    call NewSoundEnvironment("Default")
    call SetAmbientDaySound("NorthrendDay")
    call SetAmbientNightSound("NorthrendNight")
    call SetMapMusic("Music", true, 0)
    call InitSounds()
    call CreateRegions()
    call InitTechTree()
    call CreateAllUnits()
    call InitBlizzard()


    call InitGlobals()

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName("TRIGSTR_001")
    call SetMapDescription("TRIGSTR_003")
    call SetPlayers(16)
    call SetTeams(16)
    call SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)

    call DefineStartLocation(0, 4032.0, 1408.0)
    call DefineStartLocation(1, 4032.0, 1408.0)
    call DefineStartLocation(2, - 10048.0, 1792.0)
    call DefineStartLocation(3, 4032.0, 1408.0)
    call DefineStartLocation(4, 4032.0, 1408.0)
    call DefineStartLocation(5, 4032.0, 1408.0)
    call DefineStartLocation(6, 18240.0, 1728.0)
    call DefineStartLocation(7, 4032.0, 1408.0)
    call DefineStartLocation(8, 16192.0, 1728.0)
    call DefineStartLocation(9, - 7744.0, 1728.0)
    call DefineStartLocation(10, 4032.0, 1408.0)
    call DefineStartLocation(11, 4032.0, 1408.0)
    call DefineStartLocation(12, 4032.0, 1408.0)
    call DefineStartLocation(13, 4032.0, 1408.0)
    call DefineStartLocation(14, 4032.0, 1408.0)
    call DefineStartLocation(15, 4032.0, 1408.0)

    // Player setup
    call InitCustomPlayerSlots()
    call InitCustomTeams()
    call InitAllyPriorities()
endfunction




//Struct method generated initializers/callers:

